
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ali
  password: alidb
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: loan_tracker_development

test:
  <<: *default
  database: loan_tracker_test

production:
  <<: *default
  database: loan_tracker_production
  username: loan_tracker
  password: <%= ENV['LOAN_TRACKER_DATABASE_PASSWORD'] %>
